
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Rkna_Project.Models
{
    using Rkna_Project.MetaData;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(Area_TableMeta))]
public partial class Area_Table
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Area_Table()
    {

        this.Slut_Table = new HashSet<Slut_Table>();

    }


    public int Area_ID { get; set; }

    public int States_ID { get; set; }

    public string Area_Name { get; set; }

    public string Area_Desc { get; set; }

    public string Area_X_Point { get; set; }

    public string Area_Y_Point { get; set; }

    public string Area_Manger { get; set; }

    public decimal Area_Hour_Rate { get; set; }

    public System.TimeSpan Area_Start_Time { get; set; }

    public System.TimeSpan Area_End_Time { get; set; }

    public Nullable<bool> Deleted { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

    public virtual AspNetUser AspNetUser1 { get; set; }

    public virtual States_Table States_Table { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Slut_Table> Slut_Table { get; set; }

}

}
