
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Rkna_Project.Models
{
    using Rkna_Project.MetaData;
    using System;
    using System.Collections.Generic;

    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(Governorate_TableMeta))]

    public partial class Governorate_Table
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Governorate_Table()
    {

        this.States_Table = new HashSet<States_Table>();

    }


    public int Gov_ID { get; set; }

    public string Gov_Name { get; set; }

    public string Gov_Desc { get; set; }

    public string Gov_X_Point { get; set; }

    public string Gov_Y_Point { get; set; }

    public Nullable<bool> Deleted { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<States_Table> States_Table { get; set; }

}

}
