
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Rkna_Project.Models
{
    using Rkna_Project.MetaData;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(Slut_TableMeta))]
    public partial class Slut_Table
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Slut_Table()
    {

        this.Customer_Slut_Table = new HashSet<Customer_Slut_Table>();

    }


    public int Slut_ID { get; set; }

    public int Area_ID { get; set; }

    public string Name { get; set; }

    public string Slut_Level { get; set; }

    public string Slut_X_Point { get; set; }

    public string Slut_Y_Point { get; set; }

    public bool Slut_State { get; set; }

    public Nullable<bool> Deleted { get; set; }



    public virtual Area_Table Area_Table { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Customer_Slut_Table> Customer_Slut_Table { get; set; }

}

}
